In [1]:
import torch
import torchvision
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Linear Regression Model basic

In [6]:
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

print(w, b)

tensor([[-0.3195,  0.6641,  1.6799],
        [ 0.3350, -0.3855, -1.6472]], requires_grad=True) tensor([-1.7746,  0.1151], requires_grad=True)


In [7]:
def model(x):
    return x @ w.t() + b

In [8]:
preds = model(inputs)

print(f"Prediction {preds}", f"\n\nTargets {targets}")

Prediction tensor([[  91.6322,  -72.0896],
        [ 135.1055, -108.7470],
        [ 156.8517, -117.9358],
        [  56.3491,  -43.2402],
        [ 157.5268, -129.0838]], grad_fn=<AddBackward0>) 

Targets tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Loss Function

In [9]:
# Mse loss

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss

loss = mse(preds, targets)

print(loss)

tensor(20491.8965, grad_fn=<DivBackward0>)


In [11]:
# Compute gradient
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[-0.3195,  0.6641,  1.6799],
        [ 0.3350, -0.3855, -1.6472]], requires_grad=True)
tensor([[  3616.7603,   3786.4692,   2455.6248],
        [-15318.6445, -17773.9043, -10884.5391]])


In [13]:
# Adjust weights & reset gradients

with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [14]:
print(w)
print(b)

tensor([[-0.3557,  0.6262,  1.6554],
        [ 0.4882, -0.2077, -1.5384]], requires_grad=True)
tensor([-1.7750,  0.1170], requires_grad=True)


In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(14094.9189, grad_fn=<DivBackward0>)


In [16]:
# Train for 100 epochs
for i in range(500):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [17]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(93.9737, grad_fn=<DivBackward0>)


In [18]:
preds = model(inputs)

print(f"Prediction {preds}", f"\n\nTargets {targets}")

Prediction tensor([[ 56.4186,  71.8402],
        [ 86.4439,  92.3096],
        [110.2514, 149.5120],
        [ 18.9504,  44.8502],
        [110.1841, 100.0449]], grad_fn=<AddBackward0>) 

Targets tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Linear regression with pytorch built-in

In [19]:
import torch.nn as nn

In [20]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# Dataset and Dataloader

In [21]:
from torch.utils.data import TensorDataset

In [22]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:2]

(tensor([[73., 67., 43.],
         [91., 88., 64.]]), tensor([[ 56.,  70.],
         [ 81., 101.]]))

In [23]:
from torch.utils.data import DataLoader

In [24]:
batch_size = 5

train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [25]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [103., 119.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]])


In [26]:
model = nn.Linear(3, 2) # nn.Linear(input_size, output_size)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4250,  0.3103,  0.3903],
        [-0.5216,  0.2486, -0.1448]], requires_grad=True)
Parameter containing:
tensor([-0.0479,  0.3331], requires_grad=True)


In [27]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.4250,  0.3103,  0.3903],
         [-0.5216,  0.2486, -0.1448]], requires_grad=True),
 Parameter containing:
 tensor([-0.0479,  0.3331], requires_grad=True)]

In [28]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 68.5508, -27.3165],
        [ 90.9131, -34.5260],
        [101.1454, -20.1346],
        [ 71.0882, -47.5421],
        [ 86.3862, -21.9297],
        [ 68.5508, -27.3165],
        [ 90.9131, -34.5260],
        [101.1454, -20.1346],
        [ 71.0882, -47.5421],
        [ 86.3862, -21.9297],
        [ 68.5508, -27.3165],
        [ 90.9131, -34.5260],
        [101.1454, -20.1346],
        [ 71.0882, -47.5421],
        [ 86.3862, -21.9297]], grad_fn=<AddmmBackward>)

In [29]:
# Loss Function
import torch.nn.functional as F

In [30]:
loss_fn = F.mse_loss

In [31]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8155.6807, grad_fn=<MseLossBackward>)


In [32]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [33]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

In [34]:
fit(500, model, loss_fn, opt, train_dl)

Epoch [10/500], Loss: 427.9590
Epoch [20/500], Loss: 155.0959
Epoch [30/500], Loss: 147.5551
Epoch [40/500], Loss: 163.1010
Epoch [50/500], Loss: 24.6837
Epoch [60/500], Loss: 48.6581
Epoch [70/500], Loss: 68.0247
Epoch [80/500], Loss: 33.4394
Epoch [90/500], Loss: 27.4687
Epoch [100/500], Loss: 18.4427
Epoch [110/500], Loss: 22.9665
Epoch [120/500], Loss: 26.4744
Epoch [130/500], Loss: 22.3855
Epoch [140/500], Loss: 14.3072
Epoch [150/500], Loss: 19.8253
Epoch [160/500], Loss: 11.5720
Epoch [170/500], Loss: 19.3772
Epoch [180/500], Loss: 6.2730
Epoch [190/500], Loss: 12.8703
Epoch [200/500], Loss: 12.5122
Epoch [210/500], Loss: 5.4815
Epoch [220/500], Loss: 12.4180
Epoch [230/500], Loss: 8.0758
Epoch [240/500], Loss: 4.6220
Epoch [250/500], Loss: 9.0785
Epoch [260/500], Loss: 9.3179
Epoch [270/500], Loss: 6.4085
Epoch [280/500], Loss: 9.7214
Epoch [290/500], Loss: 5.5769
Epoch [300/500], Loss: 7.8809
Epoch [310/500], Loss: 3.4573
Epoch [320/500], Loss: 6.5477
Epoch [330/500], Loss: 6.

In [35]:
preds = model(inputs)

print(f"Prediction {preds}", f"\n\nTargets {targets}")

Prediction tensor([[ 57.2295,  70.5175],
        [ 81.8159,  99.4701],
        [119.6163, 135.4120],
        [ 21.3544,  37.7149],
        [101.0605, 116.7047],
        [ 57.2295,  70.5175],
        [ 81.8159,  99.4701],
        [119.6163, 135.4120],
        [ 21.3544,  37.7149],
        [101.0605, 116.7047],
        [ 57.2295,  70.5175],
        [ 81.8159,  99.4701],
        [119.6163, 135.4120],
        [ 21.3544,  37.7149],
        [101.0605, 116.7047]], grad_fn=<AddmmBackward>) 

Targets tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
