In [1]:
import torch
import torchvision
import numpy as np

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
x1 = torch.from_numpy(inputs)
y = torch.from_numpy(targets)

In [5]:
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad= True)

In [6]:
def model(x):
    return x1 @ w.t() + b

In [7]:
preds = model(x1)
preds

tensor([[  93.2286, -170.6971],
        [ 124.4647, -212.8598],
        [ 163.9078, -338.1573],
        [  74.7671, -130.9647],
        [ 129.5776, -214.5589]], grad_fn=<AddBackward0>)

In [8]:
# Mse loss

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [9]:
loss = mse(preds, y)

print(loss)

tensor(52668.8555, grad_fn=<DivBackward0>)


In [10]:
loss.backward()

In [11]:
print(w.grad)

tensor([[  3559.2107,   3431.4587,   2160.0076],
        [-25454.1562, -29225.1172, -17465.5898]])


In [12]:
import torch.nn as nn

In [13]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [15]:
from torch.utils.data import TensorDataset, DataLoader

In [16]:
train_ds = TensorDataset(inputs, targets)

In [19]:
train_ds[0:2]

(tensor([[73., 67., 43.],
         [91., 88., 64.]]), tensor([[ 56.,  70.],
         [ 81., 101.]]))

In [20]:
train_dl = DataLoader(train_ds, batch_size=5, shuffle=True)

In [21]:
for x,y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [103., 119.]])


In [23]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3361,  0.1942,  0.0862],
        [-0.0434, -0.2883,  0.4184]], requires_grad=True)
Parameter containing:
tensor([-0.1405, -0.5200], requires_grad=True)


In [24]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3361,  0.1942,  0.0862],
         [-0.0434, -0.2883,  0.4184]], requires_grad=True),
 Parameter containing:
 tensor([-0.1405, -0.5200], requires_grad=True)]

In [25]:
preds = model(x1)
preds

tensor([[ -7.9581,  -5.0165],
        [ -8.1201,  -3.0669],
        [  1.6401, -18.6656],
        [-22.8818,  -1.8660],
        [  1.3440,  -1.9083]], grad_fn=<AddmmBackward>)

In [26]:
mse(preds, y)

tensor(7779.6147, grad_fn=<DivBackward0>)

In [27]:
import torch.nn.functional as F

In [28]:
loss_fn = F.mse_loss

In [29]:
loss = loss_fn(preds, y)

In [30]:
loss

tensor(7779.6147, grad_fn=<MseLossBackward>)

In [31]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    for epoch in range(num_epochs):
        
        for xb,yb in train_dl:
            preds = model(xb)
            
            loss = loss_fn(yb, preds)
            
            loss.backward()
            
            opt.step()
            
            opt.zero_grad()
            
        